### PR TITLE
release 1.5.0

### PR DESCRIPTION
**Pull request by mikemorency**
##### SUMMARY
Creating release 1.5.0

##### ISSUE TYPE
- Release Pull Request

### CODE REVIEW

**Review by mariolenz — APPROVED** [review]
LGTM

**Comment by mariolenz** [comment]
It would be really great to see this release in time for the next Ansible Community Package (ETA next Tuesday).

Not so much because it would allow me to deprecate two modules in [community.vmware](https://github.com/ansible-collections/community.vmware), because I'm not sure if I would find the time for this. But because of allowing people to use an action group (#59). I think it's really helpful for users.

**Review by bardielle — APPROVED** [review]

**Review by anna-savina — APPROVED** [review]
LGTM

**Comment by mariolenz** [comment]
Anyone around who could do the 1.5.0 release?

**Pull request merged**
