### PR TITLE
Fix CI sanity tests

### PR DESCRIPTION
**Pull request by mariolenz**
##### SUMMARY
The unit tests look better now, but there are still problems with the sanity tests. It looks like the doc fragment is missing.

This won't fix the sanity tests, I think we'll see some new issues once this is merged. But one thing at a time.

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
cluster
cluster_drs
cluster_ha
vm_vm_drs_rule
plugins/module_utils/vmware.py
tests/integration/targets/cluster/playbook.yml
tests/unit/plugins/modules/common/utils.py

##### ADDITIONAL INFORMATION
#5

### CODE REVIEW

**Comment by mariolenz** [comment]
There are now some `unused-import` and `undocumented-parameter` errors, but I don't understand why I don't see them in `community.vmware` :shrug:

I'll have a closer look at them once this is merged.

**Comment by mariolenz** [comment]
At least the sanity tests succeed now. No idea what's wrong with the other tests, there aren't similar ones in community.vmware. So I don't know if I can help there.

But the sanity tests look OK now :tada:

**Review by machacekondra — APPROVED** [review]

**Comment by mariolenz** [comment]
@bardielle @machacekondra So, what should we do with this PR? Merge it so at least the sanity tests succeed? Or do you have any other plans?

**Review by bardielle — APPROVED** [review]

**Comment by machacekondra** [comment]
> @bardielle @machacekondra So, what should we do with this PR? Merge it so at least the sanity tests succeed? Or do you have any other plans?

Thank you @mariolenz . I will take a look at the rest of the failures.

**Pull request merged**
